#!/usr/bin/env bash
# Installs, configures, and starts the server
# HTTP 301 move permanent
# install the Nginx
sudo apt-get update
sudo apt-get -y install nginx
# enable pass pf traffic in the port 80
sudo ufw allow 'Nginx HTTP'

mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
# copy the content in the index.html file tee cuz > or >> dont work
echo 'Hello World!' |sudo tee /var/www/html/index.html
# adding a new line inside /etc/ngix/sites-available
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://codeforwin.org/c-programming-examples-exercises-solutions-beginners permanent;
	}
}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
