#!/usr/bin/env bash
# script for fix problem stop process instead of kill it
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
