#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash. 

lst=$(ls)
for a in $lst; do
  echo "$a" | cut -d '-' -f2
done
